### ISSUE TITLE
cmake-error: tbb not found

### ISSUE THREAD

**Issue by GuidoSchmidt** [ofnode/ofApp#1]
When building ofApp, I always get this error using ofaddon(ofxOpenCv) in CMakeLists.txt:

```
[...]
-- checking for module 'tbb'
--   package 'tbb' not found
CMake Error at /usr/share/cmake-3.1/Modules/FindPkgConfig.cmake:340 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.1/Modules/FindPkgConfig.cmake:502 (_pkg_check_modules_internal)
  /home/guido/Development/code/ofnode/of/openFrameworks.cmake:539 (pkg_check_modules)
  CMakeLists.txt:10 (ofxaddon)
```

Do you have any idea, why it can't be found? It is installed and openframeworks with make-build system works using the ofxOpenCv addon.

**Comment by procedural** [comment]
Run these commands to diagnose where tbb is located on your machine and reply with their outputs:

1) `file /usr/lib/pkgconfig/tbb.pc`

2) `sudo updatedb -l 0 && locate -i tbb.pc`

3) `pkg-config tbb --libs`

4) `sudo updatedb -l 0 && locate -i libtbb.so`

**Comment by procedural** [comment]
Also, which distro do you use?

**Comment by GuidoSchmidt** [comment]
Im on x86_64 arch linux. Seems that the intel-tbb package i have installed does not provide a tbb.pc file.  I actually copied the tbb.pc from here [apt-browse.org](http://apt-browse.org/browse/ubuntu/trusty/universe/amd64/libtbb-dev/4.2~20130725-1.1ubuntu1/file//usr/lib/pkgconfig/tbb.pc/) and customized it, which worked pretty well. But after all I get linker errors from ld:

```
[ 53%] Built target ofxOpenCv
[ 61%] Generating CXX unity source cotire/ofApp_CXX_unity.cxx
[ 69%] Generating CXX prefix source cotire/ofApp_CXX_prefix.cxx
[ 76%] Generating CXX prefix header cotire/ofApp_CXX_prefix.hxx
[ 84%] Building CXX precompiled header cotire/ofApp_CXX_prefix.hxx.gch
[ 92%] [100%] Building CXX object CMakeFiles/ofApp.dir/src/ofApp.cpp.o
Building CXX object CMakeFiles/ofApp.dir/src/main.cpp.o
Linking CXX executable ../bin/ofApp
/usr/bin/ld: cannot find -lopencv_calib3d
/usr/bin/ld: cannot find -lopencv_contrib
/usr/bin/ld: cannot find -lopencv_core
/usr/bin/ld: cannot find -lopencv_features2d
/usr/bin/ld: cannot find -lopencv_flann
/usr/bin/ld: cannot find -lopencv_gpu
/usr/bin/ld: cannot find -lopencv_highgui
/usr/bin/ld: cannot find -lopencv_imgproc
/usr/bin/ld: cannot find -lopencv_legacy
/usr/bin/ld: cannot find -lopencv_ml
/usr/bin/ld: cannot find -lopencv_nonfree
/usr/bin/ld: cannot find -lopencv_objdetect
/usr/bin/ld: cannot find -lopencv_ocl
/usr/bin/ld: cannot find -lopencv_photo
/usr/bin/ld: cannot find -lopencv_stitching
/usr/bin/ld: cannot find -lopencv_superres
/usr/bin/ld: cannot find -lopencv_video
/usr/bin/ld: cannot find -lopencv_videostab
/usr/bin/ld: cannot find -ltbb
/usr/bin/ld: cannot find -lXext
/usr/bin/ld: cannot find -lX11
/usr/bin/ld: cannot find -lICE
/usr/bin/ld: cannot find -lSM
/usr/bin/ld: cannot find -lGL
/usr/bin/ld: cannot find -lGLU
/usr/bin/ld: cannot find -lrt
collect2: Fehler: ld gab 1 als Ende-Status zurück
CMakeFiles/ofApp.dir/build.make:268: die Regel für Ziel „../bin/ofApp“ scheiterte
make[2]: *** [../bin/ofApp] Fehler 1
CMakeFiles/Makefile2:122: die Regel für Ziel „CMakeFiles/ofApp.dir/all“ scheiterte
make[1]: *** [CMakeFiles/ofApp.dir/all] Fehler 2
Makefile:76: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2
```

**Comment by procedural** [comment]
Yeah, that's messed up :) Are you using standard Arch Linux or distro like Manjaro? I'll try to reproduce it on setup like yours

**Comment by GuidoSchmidt** [comment]
Using default Arch, i will also try to find out what's going wrong. Thanks in advance :+1:

**Comment by procedural** [comment]
I've compiled ofApp on freshly installed Arch Linux today, so linker errors like
```bash
/usr/bin/ld: cannot find -lX11
```
are really strange because A) I'm checking X11 with REQUIRED flag and it would throw an error at project generation step if it wasn't be found (there also should be `-- Found X11: /usr/lib64/libX11.so` line when running `cmake .. -G Ninja` command) and B) libX11.so should be always installed on the system, if it's not pure Wayland or something... Try to find it with these commands:
```bash
sudo pacman -Syu mlocate
sudo updatedb -l 0
sudo locate -i libX11.so
```
Here's my output for example:
```bash
/usr/lib/libX11.so
/usr/lib/libX11.so.6
/usr/lib/libX11.so.6.3.0
```

As for OpenCV, indeed, there's no tbb.pc file in the system available by default so I will move its find step to CMake rather than piggybacking it on pkg-config and will try to test it on Arch today.

**Comment by procedural** [comment]
Also, for X11 development files you can try to install these packages that I have on my Arch:
```bash
sudo pacman -Syu xorg-server xorg-server-common xorg-server-devel xorg-server-utils
```
I should probably add them to `dev/install/linux/archlinux.sh` script...

**Comment by GuidoSchmidt** [comment]
Ok, figured out what went wrong :smiley: ... seems that the first `-Wl` linker parameter in line 
```list(APPEND OFXADDONS_LIBRARIES -Wl,-Bstatic ${OPENCV_LDFLAGS} -Wl,-Bdynamic)```
was the problem, messing around with comma separation. It works now and I'm petty happy with it (If you like you cann pull from my fork)

Thanks for your work btw, I really appreciate the CMake build system for of.

**Comment by procedural** [comment]
@GuidoSchmidt Thank you! I'll merge it today, but before I think we can get rid of  `-Wl,-Bstatic` and `-Wl,-Bdynamic` flags for `${OPENCV_LDFLAGS}` since it seems static OpenCV packages are available only on Ubuntu, I think Arch and other distros might not have them in their main repos.

**Comment by procedural** [comment]
Or we can check if the system is Ubuntu based, but I wonder if it's possible in CMake at all?..

**Comment by GuidoSchmidt** [comment]
Not sure, weather CMake can detect the systems os type... could be worth a look

**Comment by GuidoSchmidt** [comment]
The cmake project compiled without errors on my virtual machine running Ubuntu 14.04 32bit :+1:
