### ISSUE TITLE
Let CMake scan recursively for source-files

### ISSUE THREAD

**Issue by GuidoSchmidt** [ofnode/ofApp#2]
Hey,
I'm currently working with your openframeworks CMake-Build and realy like it so far. Actually when writing custom classes, it would be nice if CMake would find the files automatically from the `src` folder. This could be achieved by replacing:

```
set(SOURCES
    src/main.cpp
    src/ofApp.cpp
)
```

in the CMakeLists.txt with the following:
```
file(
    GLOB_RECURSE SOURCES
    src/*.hpp
    src/*.h
    src/*.cpp
)
```

The script will then compile all header and C++ source files located in the `src` folder.

**Comment by procedural** [comment]
If project is already generated, you have to regenerate it each time on adding new source files. That's annoying to do if you know that you can simply name them and compile without an extra step.

**Comment by GuidoSchmidt** [comment]
Oh nice, didn't know that, that's pretty handy. Thanks for the clarification.
