### ISSUE TITLE
undefined symbol: glewExperimental

### ISSUE THREAD

**Issue by mrzl** [ofnode/ofApp#3]
Hey, many thanks in advance for getting the cmake support started/done for of.

Anyhow, I am running into the problem that I can't start the cmake compiled binary. The steps I performed are:
1. Cloning, compiling your of repository -> no errors whatsoever
2. Cloning, compiling your ofApp repository -> no errors whatsoever
3. Running the compiled binary results in this:

~/Downloads/of_v0.8.4_linux64_release/ofApp/bin (master)$ ./ofApp 
./ofApp: symbol lookup error: ~/Downloads/of_v0.8.4_linux64_release/of/lib-linux/release-64/libopenFrameworks.so: undefined symbol: glewExperimental

Did you come across this already? Do you have a hint what this could be related to?

Many thanks already,
Marcel

**Comment by procedural** [comment]
@mrzl thanks for reporting this!

I've just compiled OF on freshly installed Ubuntu 14.04 and it linked fine, so I can't repro this. To figure out why it can't find `glewExperimental` symbol on your setup we will need to test a few things:

Could you open a terminal window, change directory to `of/lib-linux/release-64` and run this line:

```bash
nm --no-sort --defined-only libglew.so | grep glewExperimental
```

Here's my output for example, `B` means it's defined:

```
$ nm --no-sort --defined-only libglew.so | grep glewExperimental
000000000009e106 B glewExperimental
```

If it will show nothing, could you run just:

```bash
nm --no-sort --defined-only libglew.so
```

And paste here all the symbols?

**Comment by mrzl** [comment]
Thanks for the quick reply @procedural Here you go:
http://pastebin.com/v40RPY7t

**Comment by procedural** [comment]
@mrzl thanks, so `glewExperimental` is defined in `libglew.so`, interesting...

For a temporary test / workaround, could you place all `.so` libraries from `of/lib-linux/release-64` to `ofApp/bin` directory and try to run the app?

**Comment by mrzl** [comment]
deploy@marchi:~/Downloads/of_v0.8.4_linux64_release/ofApp/bin (master)$ ls -l
total 30652
-rw-rw-r-- 1 deploy deploy  161349 Aug 11 17:56 glew.txt
-rwxrwxr-x 1 deploy deploy 7568232 Aug 11 17:56 libfreeimage.so
-rw-rw-r-- 1 deploy deploy  925060 Aug 11 17:56 libglew.a
-rwxrwxr-x 1 deploy deploy  796272 Aug 11 17:56 libglew.so
-rwxrwxr-x 1 deploy deploy  116120 Aug 11 17:56 libglfw.so
-rwxrwxr-x 1 deploy deploy  116120 Aug 11 17:56 libglfw.so.3
-rwxrwxr-x 1 deploy deploy  116120 Aug 11 17:56 libglfw.so.3.1
-rwxrwxr-x 1 deploy deploy   16880 Aug 11 17:56 libkissfft.so
-rwxrwxr-x 1 deploy deploy 6126632 Aug 11 17:56 libopenFrameworks.so
-rwxrwxr-x 1 deploy deploy  187688 Aug 11 17:56 libPocoCrypto.so
-rwxrwxr-x 1 deploy deploy  187688 Aug 11 17:56 libPocoCrypto.so.40
-rwxrwxr-x 1 deploy deploy 2471704 Aug 11 17:56 libPocoFoundation.so
-rwxrwxr-x 1 deploy deploy 2471704 Aug 11 17:56 libPocoFoundation.so.1.7.0
-rwxrwxr-x 1 deploy deploy 2471704 Aug 11 17:56 libPocoFoundation.so.40
-rwxrwxr-x 1 deploy deploy  402312 Aug 11 17:56 libPocoJSON.so
-rwxrwxr-x 1 deploy deploy  402312 Aug 11 17:56 libPocoJSON.so.40
-rwxrwxr-x 1 deploy deploy 1522960 Aug 11 17:56 libPocoNet.so
-rwxrwxr-x 1 deploy deploy 1522960 Aug 11 17:56 libPocoNet.so.40
-rwxrwxr-x 1 deploy deploy  370904 Aug 11 17:56 libPocoNetSSL.so
-rwxrwxr-x 1 deploy deploy  370904 Aug 11 17:56 libPocoNetSSL.so.40
-rwxrwxr-x 1 deploy deploy  603720 Aug 11 17:56 libPocoUtil.so
-rwxrwxr-x 1 deploy deploy  603720 Aug 11 17:56 libPocoUtil.so.40
-rwxrwxr-x 1 deploy deploy  786032 Aug 11 17:56 libPocoXML.so
-rwxrwxr-x 1 deploy deploy  786032 Aug 11 17:56 libPocoXML.so.40
-rwxrwxr-x 1 deploy deploy  109168 Aug 11 17:56 librtaudio.so
-rwxrwxr-x 1 deploy deploy   48568 Aug 11 17:56 libtess2.so
-rwxrwxr-x 1 deploy deploy   76344 Aug 11 16:09 ofApp
deploy@marchi:~/Downloads/of_v0.8.4_linux64_release/ofApp/bin (master)$ ./ofApp 
./ofApp: symbol lookup error: /home/deploy/Downloads/of_v0.8.4_linux64_release/ofApp/bin/libopenFrameworks.so: undefined symbol: glewExperimental

**Comment by procedural** [comment]
Why `libglew.a` there? OF shouldn't build it by default, could you delete it from `of/lib-linux/release-64` folder and recompile OF?

**Comment by procedural** [comment]
Also, could you print the output of:

```
objdump -x libopenFrameworks.so | grep NEEDED
```

**Comment by mrzl** [comment]
In the process of recompiling.

The output of the objdum is:
  NEEDED               libstdc++.so.6
  NEEDED               libm.so.6
  NEEDED               libgcc_s.so.1
  NEEDED               libc.so.6
  NEEDED               ld-linux-x86-64.so.2

**Comment by mrzl** [comment]
The compilation is stuck at this point for quiete a while:
-- Configuring done
-- Generating done
-- Build files have been written to: /home/deploy/Downloads/of_v0.8.4_linux64_release/of/build-linux
deploy@marchi:~/Downloads/of_v0.8.4_linux64_release/of/build-linux (master)$ ninja
[938/939] Creating library symlink ../lib-linux/release-64/libPocoNetSSL.so

**Comment by procedural** [comment]
> [938/939] Creating library symlink ../lib-linux/release-64/libPocoNetSSL.so
Yea! That's a known problem, Clang can't compile GLEW for some reason, it's actually stuck on `glew.c` if you Ctrl + C and repeat the compiling it will show the file...

So you used a method for compiling libglew.so and libglew.a from [known issues gist page](https://gist.github.com/procedural/0470684110f443ce3f01)?

**Comment by mrzl** [comment]
Yeah, I forgot to mention that earlier. I did try compiling glew separately. I deleted it and just recompiled of and ofApp. After waiting a while it eventually finished the of compilation successfully:
deploy@marchi:~/Downloads/of_v0.8.4_linux64_release/of/build-linux (master)$ ninja
[939/939] Linking C shared library ../lib-linux/release-64/libglew.so

Now I reconfigured and recompiled ofApp, too, but the symbol lookup error persists.

**Comment by procedural** [comment]
try run this line before executing an app:

```
export LD_LIBRARY_PATH=.
./ofApp
```

**Comment by mrzl** [comment]
Sorry for just pasting the commands, I have the feeling that expressed it best

deploy@marchi:~/Downloads/of_v0.8.4_linux64_release/ofApp/bin (master)$ ls
ofApp
deploy@marchi:~/Downloads/of_v0.8.4_linux64_release/ofApp/bin (master)$ ./ofApp 
./ofApp: symbol lookup error: /home/deploy/Downloads/of_v0.8.4_linux64_release/of/lib-linux/release-64/libopenFrameworks.so: undefined symbol: glewExperimental
deploy@marchi:~/Downloads/of_v0.8.4_linux64_release/ofApp/bin (master)$ export LD_LIBRARY_PATH=.
deploy@marchi:~/Downloads/of_v0.8.4_linux64_release/ofApp/bin (master)$ ./ofApp 
./ofApp: symbol lookup error: /home/deploy/Downloads/of_v0.8.4_linux64_release/of/lib-linux/release-64/libopenFrameworks.so: undefined symbol: glewExperimental
deploy@marchi:~/Downloads/of_v0.8.4_linux64_release/ofApp/bin (master)$ cp ../../of/lib-linux/release-64/* .
deploy@marchi:~/Downloads/of_v0.8.4_linux64_release/ofApp/bin (master)$ ./ofApp 
./ofApp: symbol lookup error: ./libopenFrameworks.so: undefined symbol: glewExperimental

**Comment by mrzl** [comment]
Whoops, that looks ugly. So I tried it again, ending up with the same thing.

**Comment by procedural** [comment]
> Sorry for just pasting the commands, I have the feeling that expressed it best

I wish *everyone* would do that :) I mean, it's not a paper, we have an infinite white space here, paste all the things...

Ok, you know what... Enough of this guess game I think, that's actually bizzare why `libopenFrameworks.so` can't find the symbol which is right fucking next to it, in `libglew.so`... I'll make a change to OF right now which will compile `glew.c` with the rest of `libopenFrameworks.so`.

**Comment by mrzl** [comment]
Hummm, I see. It's reptty strange because the compilation runs seamlessly.

**Comment by procedural** [comment]
What's going on here... O__o

On my machine `of/src/glew/include/GL/glew.h` has **19743** lines, github shows only **9899** lines: https://github.com/ofnode/of/blob/master/src/glew/include/GL/glew.h#L9899

`git status` shows that my local repo is synced...

What???

**Comment by procedural** [comment]
@mrzl copy and replace `of/src/glew/include/GL/glew.h` with [my glew.h file](https://gist.github.com/procedural/703010dfde68e43cde4c) and see if it works

**Comment by procedural** [comment]
Hahaha, no, wait, it seems even gist can handle only **18096** lines out of **19743**

**Comment by mrzl** [comment]
OMG. Well, pastebin that monster to me.

**Comment by procedural** [comment]
Hahahaha!

![](http://i.imgur.com/QGques5.png)

21 century, everyone! Should I torrent you a textfile or something? :D

**Comment by procedural** [comment]
Try it! https://mega.co.nz/#!FFIQRYBJ!1OryroXuEOFfh9rdQo-6bp9DcLe_mItEJq8z3tI6qhY

**Comment by procedural** [comment]
@mrzl I'm thinking maybe Github just truncates the file visually when accessed from website, and cloned normally, in which case the result will be the same

**Comment by mrzl** [comment]
To be honest, I don't think github truncates things, check this out:
https://github.com/openframeworks/openFrameworks/blob/master/libs/glew/include/GL/glew.h#L18984

I'm in the process of compiling.....

**Comment by procedural** [comment]
@mrzl looks like raw version shown fine: https://raw.githubusercontent.com/ofnode/of/master/src/glew/include/GL/glew.h

**Comment by mrzl** [comment]
Yeah, seems like it. Recompiling with your mega glew.h didn't change a thing. I have no idea what it could be...

**Comment by procedural** [comment]
@mrzl me too, the idea of compiling glew.c with openFrameworks is not perfect either because Clang can't handle it, so I'll make an exception for glew to compile it always statically.

**Comment by procedural** [comment]
One thing I can't understand and it'll be awesome to know the answer for:

In `of/src/openframeworks` folder `glewExperimental` is referred only in two places:

```
app/ofAppGLFWWindow.cpp:246:		glewExperimental = GL_TRUE;
app/ofAppGlutWindow.cpp:267:	glewExperimental = GL_TRUE;
```

So that's an assignment. It would throw an error if `glewExperimental` was not defined. It didn't, so it was indeed defined somewhere. Where? Changing directory to `of/src/glew` and searching for `glewExperimental` reveals this:

```
doc/basic.html:195:situation, the <tt>glewExperimental</tt> global switch can be turned
include/GL/glew.h:19716:GLEWAPI GLboolean glewExperimental;
src/glew.c:9341:  if (glewExperimental || GLEW_VERSION_1_2) GLEW_VERSION_1_2 = !_glewInit_GL_VERSION_1_2(GLEW_CONTEXT_ARG_VAR_INIT);
src/glew.c:9346:  if (glewExperimental || GLEW_VERSION_1_3) GLEW_VERSION_1_3 = !_glewInit_GL_VERSION_1_3(GLEW_CONTEXT_ARG_VAR_INIT);
...
src/glew.c:13354:  if (glewExperimental || GLXEW_SUN_get_transparent_index) GLXEW_SUN_get_transparent_index = !_glewInit_GLX_SUN_get_transparent_index(GLEW_CONTEXT_ARG_VAR_INIT);
src/glew.c:13358:  if (glewExperimental || GLXEW_SUN_video_resize) GLXEW_SUN_video_resize = !_glewInit_GLX_SUN_video_resize(GLEW_CONTEXT_ARG_VAR_INIT);
src/glew.c:13398:GLboolean glewExperimental = GL_FALSE;
src/glewinfo.c:11632:  glewExperimental = GL_TRUE;
src/visualinfo.c:128:  glewExperimental = GL_TRUE;
```

It's definition in header file:

```
include/GL/glew.h:19716:GLEWAPI GLboolean glewExperimental;
```

So it's defined in `GL/glew.h`, assigned in `ofAppGLFWWindow.cpp:246` and compiled fine. Why shared library can't find it then?..

**Comment by procedural** [comment]
Wait, what's that?..

```
src/glew.c:13398:GLboolean glewExperimental = GL_FALSE;
```

A local variable with the same name and assignment?.. Is this supposed to be there?..

**Comment by procedural** [comment]
Ok, I think I know what's the problem now, fixing it...

**Comment by procedural** [comment]
[The fix is pushed](https://github.com/ofnode/of/commit/e8fb9cc8928e5b22e9471eb6f579e82e0aac4f35), try to pull the changes and recompile libraries, preferably cleanly!

**Comment by mrzl** [comment]
Alright, everything compiles nicely, I needed to update my compiler for c++14, though. No big deal.

Does ofApp depend on boost 1.55? I can't upgrade, as I'm using another framework that depend son boost 1.54. So right now the ofApp cmake configuration fails with an empty cmake screen and doesn't seem to finish the configuration even though I'm able to generate the files.. 

deploy@marchi:~/Downloads/of_v0.8.4_linux64_release/ofApp/build (master)$ rm -R *
deploy@marchi:~/Downloads/of_v0.8.4_linux64_release/ofApp/build (master)$ ccmake .. -G ninja


deploy@marchi:~/Downloads/of_v0.8.4_linux64_release/ofApp/build (master)$ ninja
ninja: error: loading 'build.ninja': No such file or directory

**Comment by procedural** [comment]
> Does ofApp depend on boost 1.55? I can't upgrade, as I'm using another framework that depend son boost 1.54.

No, it does not. I've just checked [ubuntu.sh](https://github.com/ofnode/of/blob/master/dev/install/linux/ubuntu.sh), yeah, I probably shouldn't explicitly install it like so, I'll change that so Boost 1.54 could be default on Ubuntu 14.04.

> So right now the ofApp cmake configuration fails with an empty cmake screen and doesn't seem to finish the configuration

This is not a usual behaviour of CMake, it always should print something, at least errors. Printing nothing means something strange with CMake itself, try to [download latest version from here]() and call its executable directly from download directory.

**Comment by mrzl** [comment]
Interestingly it works with the official binary from cmake now, very strange, but that's another issue.

deploy@marchi:~/Downloads/of_v0.8.4_linux64_release/ofApp/build (master)$ rm -R *
deploy@marchi:~/Downloads/of_v0.8.4_linux64_release/ofApp/build (master)$ ~/Downloads/cmake-3.3.0-Linux-x86_64/bin/ccmake .. -G Ninja

deploy@marchi:~/Downloads/of_v0.8.4_linux64_release/ofApp/build (master)$ ninja
[9/9] Linking CXX executable ../bin/ofApp
deploy@marchi:~/Downloads/of_v0.8.4_linux64_release/ofApp/build (master)$ cd ..
deploy@marchi:~/Downloads/of_v0.8.4_linux64_release/ofApp (master)$ cd bin
deploy@marchi:~/Downloads/of_v0.8.4_linux64_release/ofApp/bin (master)$ ls
ofApp
deploy@marchi:~/Downloads/of_v0.8.4_linux64_release/ofApp/bin (master)$ ./ofApp 
./ofApp: symbol lookup error: /home/deploy/Downloads/of_v0.8.4_linux64_release/of/lib-linux/release-64/libopenFrameworks.so: undefined symbol: glewExperimental
deploy@marchi:~/Downloads/of_v0.8.4_linux64_release/ofApp/bin (master)$ ldd ofApp 
	linux-vdso.so.1 =>  (0x00007ffe96bfc000)
	libopenFrameworks.so => /home/deploy/Downloads/of_v0.8.4_linux64_release/of/lib-linux/release-64/libopenFrameworks.so (0x00007ff13ccc1000)
	libboost_system.so.1.54.0 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.54.0 (0x00007ff13cabd000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ff13c741000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff13c52a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff13c165000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff13be5f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff13d071000

The problem is still the same. So you have never experienced that problem before, right?

**Comment by procedural** [comment]
Let's try one thing, here's my compiled 64-bit libraries from Ubuntu 14.04, remove your `of/lib-linux` directory and replace it with mine: https://mega.co.nz/#!8ZJWBJqL!psr_3sybfQPOHJy08t3THHpOaMUdet98il1Mex_YNUc

**Comment by procedural** [comment]
>So you have never experienced that problem before, right?

Yes, that's why debugging this case is difficult for me. Do you have TeamViewer installed? Then I could connect to your machine directly and try few more things.

**Comment by mrzl** [comment]
I took your binaries and the problem persists. I recompiled ofApp and it worked without problems.

I'm just trying to compile it all on a different machine at the moment. I'll update here.

**Comment by procedural** [comment]
>I took your binaries and the problem persists. I recompiled ofApp and it worked without problems.

You mean my libraries worked? ofApp runs fine with them, without `glewExperimental` error?

**Comment by mrzl** [comment]
Sorry, i was in a hurry and forgot half of the info. Using your binaries, the glewExperimental error persisted, it was exactly the same behaviour. And I had the exact same behaviour on another machine of mine, so I'm wondering if I am missing something. Because it seems like you might have some special setup that's not documented. Do you think that could be the case?
If not, then I am kinda lost and will put one last effort into it later today and then leave it, I guess..

**Comment by procedural** [comment]
>Because it seems like you might have some special setup that's not documented. Do you think that could be the case?

No, I documented every step because and I do this primarily for myself so I won't forget the steps later.

Assuming the system is clean, I always:

* Clone the repo with `git clone https://github.com/ofnode/of --depth 1 --no-single-branch`
* Install all needed dependencies with [`dev/install/linux/ubuntu.sh`](https://github.com/ofnode/of/blob/master/dev/install/linux/ubuntu.sh) [I do extra there, it's required]
* Create a build directory and run `CC=clang CXX=clang++ cmake .. -G Ninja && ninja` from there
* Clone ofApp with `git clone https://github.com/ofnode/ofApp`
* Create a build directory and run `CC=clang CXX=clang++ cmake .. -G Ninja && ninja` from there

If these are not working, then they should fail on another machine. I'll find one and will try compile cleanly there today.

**Comment by procedural** [comment]
> Using your binaries, the glewExperimental error persisted

If the problem was at compile time, my libraries would solve it, but apparently we have an issue on linking stage or some missing global variable.

If it's a linker, I use only gold linker which is installed when `dev/install/linux/ubuntu.sh` is finished.

If it's a global variable, I'm not entirely familiar with them on Linux, I know only about `LD_LIBRARY_PATH`, but it didn't worked in your case.

**Comment by mrzl** [comment]
I'm just doing a complete new run-through, documenting everything I do. Give me a couple of more minutes and you'll see all details

**Comment by mrzl** [comment]
Jesus christ, it just worked now. \o/ I did literally everything the same, except that I did not clone the examples submodules.

**Comment by procedural** [comment]
> except that I did not clone the examples submodules.

That can't be a reason... :D

But anyway, it doesn't fixes the problem you have on two systems before. I vote for some sneaky global variable...

**Comment by procedural** [comment]
Or you tested it on the system which failed before the new run-through?

**Comment by mrzl** [comment]
I tested it on the system where it was working before. Super strange. I installed a couple of new packages here, but that cant be the case either, no?

deploy@marchi ~/D/of_cmake> sudo ./of/dev/install/linux/ubuntu.sh
The following packages will be upgraded:
  tzdata tzdata-java xserver-xorg-video-intel

**Comment by procedural** [comment]
> I installed a couple of new packages here, but that cant be the case either, no?

Yea, it shouldn't. Could you check if `ld --versions` returns GNU gold?

**Comment by mrzl** [comment]
$ ld -v
GNU gold (GNU Binutils for Ubuntu 2.24) 1.11

**Comment by procedural** [comment]
If only we would have some way to debug loading of shared libraries on Linux, right now it looks like a black box to me

**Comment by procedural** [comment]
[LD_DEBUG](http://www.bnikolic.co.uk/blog/linux-ld-debug.html) maybe...

**Comment by procedural** [comment]
@mrzl could you try to copy and paste ofApp binary which works to the system where it doesn't? If you replace it and the problem will still persists then we will be sure it's something about loading shared libraries at runtime

**Comment by avilleret** [comment]
I have the same issue on a fresh Ubuntu 15.04 system.
I followed the step you mention for of and ofApp (btw why you don't build ofApp with clang too ?)
I also tried several configuration (building with g++-4.9.2, g++-5, clang-3.6) none of them work.
But produce different issue.
So i'm quite disappointed :-/

**Comment by avilleret** [comment]
libopenFrameworks.so is not linking to libglew.so.
That might be the culprit.
But I'm wondering why this symbol shows up and not another one ?
~~~~
$ ldd libopenFrameworks.so 
	linux-vdso.so.1 =>  (0x00007ffebb9f6000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f77aeaad000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f77ae7a5000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f77ae58f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f77ae1c5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f77af13f000)
~~~~

**Comment by procedural** [comment]
@avilleret sorry, forgot to update the readme!

>But produce different issue.

Which issue is that? Paste here every info that can be useful.

Yeah, this issue is a hard nut. If we won't solve it this time I might replace GLEW in openFrameworks with something else, honestly.

**Comment by procedural** [comment]
@avilleret so you have this issue too:

>libopenFrameworks.so: undefined symbol: glewExperimental

right?

**Comment by avilleret** [comment]
yes exatly the same.
I'll do more test tomorrow with my fresh snapshot and let you know the exact error I get.

**Comment by procedural** [comment]
@avilleret for a workaround you can [try to comment this line](https://github.com/ofnode/of/blob/dc5badd/src/openframeworks/app/ofAppGLFWWindow.cpp#L250) tomorrow. If it will help, I think we are safe to delete it.

**Comment by avilleret** [comment]
hurra ! using exactly the same compiler for building `of` and `ofApp` works.
So the error was there I think and you can close this issue.
I'll do more test asap with other compiler.
Thanks for the work btw.

**Comment by mrzl** [comment]
@avilleret Can you give me some more detailed info of how you compiled it, please?

**Comment by avilleret** [comment]
@mrzl on a fresh Ubuntu 15.04 install, I follow the steps in of/README.md and ofApp/README.md.
please note @procedural updated the second one yesterday.

I just made another test, re-building both of and ofApp with g++ 4.9.2 instead of clang++ leads to that issue.

**Comment by procedural** [comment]
@avilleret thanks, I'll try to repro the wrong approach and see if I get the same undefined symbol error...

**Comment by avilleret** [comment]
hum...
copying the whole ofnode folder from the fresh Ubuntu 15.04 to my latptop doesn't work.
I got the same error : 
`~/ofnode/ofApp/bin$ ./ofApp 
./ofApp: symbol lookup error: /home/antoine/ofnode/of/lib-linux/release-64/libopenFrameworks.so: undefined symbol: glewExperimental`

So I think there is still something wrong in my laptop configuration.
Maybe there is a conflicting libglew somewhere that is loaded instead of the one next to libopenFrameworks.

**Comment by procedural** [comment]
Welcome to the world of dynamic dependencies, ladies and gentlemen, **the** primary reason why modern operating systems suck.

**Comment by procedural** [comment]
@mrzl @avilleret I want both of you to run this command in a folder with problematic executable so we could see the difference in loading of shared libraries at runtime on our setups:

```
LD_DEBUG_OUTPUT=rtld-debug.txt LD_DEBUG=libs ./ofApp
```

When app will be shown, close it and post the content of `rtld-debug.txt` to gist or other online service which allows sharing of large log files.

Here's mine:

[rtld-debug.txt](https://gist.github.com/procedural/e2f222addbf631813b2a)

**Comment by procedural** [comment]
Unfortunately, due to amount of (most of the times unnecessary) complexity of C++ and 3D graphics APIs such as OpenGL we can't share the log files for `LD_DEBUG=symbols` information since the log file generates for 5 or more minutes and results in a **380 MB** file.

**Comment by avilleret** [comment]
Here is the [rt-debug.txt](https://gist.github.com/avilleret/66cd0a5898a80a2ee94c) from the ofApp which throw `undefined symbol: glewExperimental`

**Comment by avilleret** [comment]
Then I remove some old packages from my Ubuntu 15.04 and restart from scratch the of and ofApp build.
It seems to find libglew.so now...
Here is the new [rtdl-debug.txt](https://gist.github.com/avilleret/6e75195c939641c29bd6)
But now it throw  `terminate called after throwing an instance of 'std::bad_alloc'`.

**Comment by procedural** [comment]
What... why... why it doesn't look for all the libraries in your first `rt-debug.txt`?.. Just compare them visually, most of the libraries are missing, it doesn't even mention them. Interesting.

So here's the story for you guys: I always was against use of shared libraries because it's universally a stupid idea in computer science. When I learned that Linux is historically started to use dynamic linking for everything I immediately knew at that point why Linux sucks in other developer's eyes. I refused to link anything dynamically for a long time, but few months ago I learned that the linkers, the most slowest software ever written by a programmers, which responsible for making executables out of separate compiled object files produced by the compiler, are extremely slow at linking big amounts of such object files, and given that static libraries are just archives for object files it was understandable why it was slow. And, since we use C++, and openFrameworks generally has a lot of dependencies, the linking was just horrible, especially on Windows with GNU binutils linker, and I couldn't deal with it. So I switched to dynamic libraries and suddenly the linking time was x2 faster than it was before with static libraries.

If you guys currently have a time-constrained project, as a workaround you can always pass `-DOF_STATIC=ON` flag to cmake at project generation step which will force to link all the libraries statically. But the cost of that will be very slow link time.

**Comment by procedural** [comment]
I think this issue might be solved since now I force linking shared libraries to other libraries on all systems now (before it was done only for Windows). I think that was the problem. Anyway, it it will happen again - reopen this issue!
