### ISSUE TITLE
ofApp fail to link when building with clang on RPi

### ISSUE THREAD

**Issue by avilleret** [ofnode/ofApp#5]
here is the error report:  

~~~~
Linking CXX executable ../bin/ofApp
/usr/bin/ld: CMakeFiles/ofApp.dir/src/main.cpp.o: référence au symbole non défini «_Znwj@@GLIBCXX_3.4»
//usr/lib/arm-linux-gnueabihf/libstdc++.so.6: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
~~~~

btw I'm using ld not gold linker

**Comment by procedural** [comment]
I call this `_Znwj@@GLIBCXX_3.4` error "thanks GNU people, you fucktards!". IIRC it means that it expect glibc version 3.4, but newer / older version was given? Have no idea how to solve it other than clean rebuild of OF and ofApp with strictly same compilers.

**Comment by procedural** [comment]
Oh, by the way, try recompile cleanly with system's Clang 3.5, that should solve it.

**Comment by avilleret** [comment]
haha, ok I'll try it again tomorrow

**Comment by procedural** [comment]
@avilleret sure. Thanks for all this work, by the way!

**Comment by avilleret** [comment]
unfortunately, building with clang 3.5.0-10+rpi1 doesn't work either.
There are plenty of "undefined reference" : https://gist.github.com/avilleret/4a78fc2eec14d3be8da4
Maybe we are missing some linking flags on RPi ?
The same work fine with g++ 4.9.2

**Comment by procedural** [comment]
Could you execute `ninja -v` command and share the output?

**Comment by procedural** [comment]
Also, did you recompiled OF and ofApp cleanly?

**Comment by avilleret** [comment]
> Could you execute ninja -v command and share the output?

I'm using Make for now, Ninja always failed on RPi, and I have more success with Make so I take this way first. I will try Ninja with Clang asap.

 > Also, did you recompiled OF and ofApp cleanly?

yes both, I removed everything in my build folder, then run cmake and make again.

**Comment by procedural** [comment]
>Ninja always failed on RPi

I see you mention this again, but what's the problem more specifically? A segfault or any fails durion compiling?

**Comment by avilleret** [comment]
Ninja build works for of now. But fails for ofApp/
Here is the log : 
https://gist.github.com/avilleret/21c9decc2fcfb444c572

**Comment by procedural** [comment]
Hmm... [People here point out](http://stackoverflow.com/a/15717370) that calling gcc or clang for compiling and linking C++ executables can cause these errors, could you check if there are `/usr/bin/g++` and `/usr/bin/clang++` available on your system?

**Comment by procedural** [comment]
Yeah, every information I find on this points that `clang++` may be missing...

**Comment by avilleret** [comment]
I think there were some issues in the of's openFrameworks.cmake file that have been fixed now.
And I made a mistake at some point when configuring that ends up using clang instead of clang++ (which is btw available in my system).
So this issue is now closed and building with Ninja on RPi works !
